### ISSUE TITLE
Make the prepending of the program slot to console/debug output an optional parameter

### ISSUE THREAD

**Issue by jeffderek** [ProfessorAire/Evands.Pellucid-Crestron#10]
`Options.Instance.UseTimestamps` lets me choose not to use the timestamps, I'd like a similar option to let me choose not to prepend the program slot.

I'd also argue it should be disabled by default.

**Comment by ProfessorAire** [comment]
I'm likely going to change this to a property that can be set with whatever optional header is desired and provide a method such as `Console Base.UseProgramSlotAsHeader()` to quickly set it to the program slot in use.

**Comment by ProfessorAire** [comment]
This will be resolved in the v1.1.0 release.
