### ISSUE TITLE
Text written to debug with braces in it does not print

### ISSUE THREAD

**Issue by jeffderek** [ProfessorAire/Evands.Pellucid-Crestron#14]
If there are braces in a string that is printed to console, that string does not print.  I'm assuming this has to do with string.Format interpreting those braces as arguments.  This makes it difficult to print json to console.

```
string s = "{string in braces}";
Debug.WriteDebugLine(this, "Trying to write s to Debug");
Debug.WriteDebugLine(this, s);
Debug.WriteDebugLine(this, "Attempt 2: {0}", s);
```

![image](https://user-images.githubusercontent.com/3788655/114416543-c9dfbd00-9b7e-11eb-995e-8e686a0f90a2.png)

**Comment by ProfessorAire** [comment]
You are correct. I should probably adjust the code to use string formatting only if the parameter array is not null or empty...
