### ISSUE TITLE
Debug headers with - character in them cannot be added to the suppression list

### ISSUE THREAD

**Issue by jeffderek** [ProfessorAire/Evands.Pellucid-Crestron#17]
Trying to add the debug header `SennheiserTCC2-3` to the debug suppression list results in the debug header `SennheiserTCC2` being added.  This should either work or generate an error that it is an invalid debug header at some point along the line.

![image](https://user-images.githubusercontent.com/3788655/114608235-772fff00-9c6b-11eb-91d1-072a75757a93.png)

**Comment by ProfessorAire** [comment]
Probably related to #18.

**Comment by ProfessorAire** [comment]
Resolved with the solution to #18.
