### ISSUE TITLE
Dump() does not use LFs properly on 4 series processors

### ISSUE THREAD

**Issue by jeffderek** [ProfessorAire/Evands.Pellucid-Crestron#26]
On 4 series processors, the Dump() function uses only Carriage Returns without Line Feeds.  For some SSH clients (openSSH) this causes improper behavior.  From discussions we've had about this, the issue probably has to do with Formatters.FormatObjectForConsole, and Environment.NewLine in 4 series.

The desired behavior
![image](https://user-images.githubusercontent.com/3788655/115757919-92d28e00-a36c-11eb-90b9-95ae63877507.png)

What you actually get
![image](https://user-images.githubusercontent.com/3788655/115757969-a120aa00-a36c-11eb-8941-be299c66fe38.png)

**Comment by ProfessorAire** [comment]
Will be resolved in the v1.1.0 release.

**Comment by jeffderek** [comment]
Looks like WriteException has the same problem.

4 series via OpenSSH
![image](https://user-images.githubusercontent.com/3788655/117375598-555a1e80-ae9d-11eb-9203-185a0a0311c3.png)

4 series via Putty
![image](https://user-images.githubusercontent.com/3788655/117375629-63a83a80-ae9d-11eb-8eaf-e46c687fc503.png)
