### ISSUE TITLE
Add the ability to output a table to console

### ISSUE THREAD

**Issue by jeffderek** [ProfessorAire/Evands.Pellucid-Crestron#5]

**Comment by ProfessorAire** [comment]
Any chance you can provide some details as to how you would expect this to work?

**Comment by jeffderek** [comment]
Open to multiple options, that's actually why I left it fairly vague.  

I want the ability to create a table.  I want to be able to colorize individual cells or the text within cells, without messing up the cell width.  I'd like headers to be obviously separate from the contents.  I want columns that are dynamically as wide as they need to be for the longest item in each column.  Something that looks like this

![image](https://user-images.githubusercontent.com/3788655/112173221-c1254800-8bcb-11eb-9373-7c05b553c54d.png)

There are any number of ways to build this, where it's the users responsibility to build each cell and then print the whole thing when done, or where the user just passes in a list of some sort.  Open to whatever makes the most sense.

**Comment by ProfessorAire** [comment]
This is available in the beta of 1.1.0.
