### ISSUE TITLE
Add overload methods to Logger.LogNotice and Logger.LogDebug to allow for better console coloring

### ISSUE THREAD

**Issue by jeffderek** [ProfessorAire/Evands.Pellucid-Crestron#52]
When writing debug messages, Progress and Success have useful color codes for making reading the console easier.  When writing log messages, those levels are not available.  I'd like to see the ability to write either debug or notice messages to the log, but have them colored with the progress or success colors when those messages are printed to the console.

**Comment by ProfessorAire** [comment]
I've added the `Logger.LogMessage` methods to hopefully meet the needs of this ticket. There are also matching extension methods.
