### ISSUE TITLE
Allow creation of terminal commands with custom names created at runtime, not just suffixes

### ISSUE THREAD

**Issue by jeffderek** [ProfessorAire/Evands.Pellucid-Crestron#54]
I'd like to be able to create a command where the entire command is created at runtime, not just the suffix.  So if I have a display that already has a declared id of `display_1` elsewhere in code, I'd like to be able to use that ID in it's entirety as the command, not just as a suffix.

Right now I pretty much have to have the command be `display` and then I have to parse out the number in the ID and use it as the suffix, which works but requires me to stick to a specific format when creating IDs.  If I could just use the ID as the command in it's entirety, I wouldn't have to do that.

Ideally I'd like my command to be `app DISPLAY_ID_HERE pwr -n` or something similar.

**Comment by ProfessorAire** [comment]
Definitely plan on doing this for a release soon.

**Comment by ProfessorAire** [comment]
In order to allow this without creating breaking changes I've added the ability to set the `TerminalCommandBase` class' `Name` property, but only prior to it being registered with any global commands, after which attempting to do so will throw an exception.
