### ISSUE TITLE
Commands listed in the help menu should be alphabetized and case-corrected

### ISSUE THREAD

**Issue by jeffderek** [ProfessorAire/Evands.Pellucid-Crestron#57]
It's entirely unclear to me what order the commands in the help menu are listed.  I originally assumed it was the order they were registered, but that doesn't actually seem to match with my code.  The registration order for the following screen shot was QSC, Switcher, Display 1, Display 2, Web.  Odd that they ended up in almost but not quite reverse order.

Regardless, they should be alphabetized.  

![image](https://user-images.githubusercontent.com/3788655/127416882-6d78278f-d3ca-4614-8d2f-d4aae137fc34.png)

Beyond that they should also probably be case corrected just to look better.  The variance between `web` and `Switcher` is my own fault in my own programming, and obviously I can take ownership of that and fix them myself, but `console` and `Debug` are part of pellucid themselves and they're not consistent either.

I have no particular feelings about what the case correction should be.  All lowercase is great until you run into something like SystemManagerForDevicesWithLongNames and then it's just a mess.   I'd probably just go with all lowercase regardless but I don't feel strongly about it.

**Comment by ProfessorAire** [comment]
I'm leaning toward alphabetized and lower case on the first character. This way it's easier to stay consistent with short commands and still let subsequent upper casing work.

This should help with most inconsistencies, without forcing too much styling on command names.

**Comment by jeffderek** [comment]
My only issue with lower case on first character is that QSCCommands would turn into qSCCommands.  Which looks _super_ dumb.  Now QSCCommands doesn't really follow any proper naming convention I'm aware of, but still.

**Comment by ProfessorAire** [comment]
My goal would be to try to be smart about that. Make the assumption that if there are multiple capped characters in a row that only the last would be capped.

```csharp
QSCCommands = qscCommands MySpecialCommand = mySpecialCommand
MYCommand = myCommand
```

It obviously won't be perfect in _every_ scenario, but hopefully most.

**Comment by jeffderek** [comment]
I like that a lot.  Good solution.

**Comment by jeffderek** [comment]
If it won't be perfect in _every_ scenario i suppose the responsible thing would be to add a flag somewhere to disable the case correction, but have it enabled by default.  Seems like something that ought to be there but nobody will ever use though, so maybe not.

**Comment by ProfessorAire** [comment]
I haven't added a flag, as I think it's sufficient for enough scenarios. This will be present in the next release.
