### ISSUE TITLE
Add support for default commands without verbs

### ISSUE THREAD

**Issue by jeffderek** [ProfessorAire/Evands.Pellucid-Crestron#7]
Assuming I create a global command called "app", I would love to be able to assign something to "app status" instead of having to create a command and a verb, a la "app monitoring status".  So perhaps a default verb?  

Open to a wide variety of implementations, mostly just interested in the ability to create commands that can be run with very few keystrokes.

**Comment by ProfessorAire** [comment]
Added the `DefaultVerbAttribute` class to allow decorating a method. Although multiple methods can use the attribute, the first one retrieved via reflection is the default that will be executed, so there's no guarantee it will be the expected command and is up to the developer to ensure the attribute is not used multiple times.
