### ISSUE TITLE
Add Alias support for commands/verbs

### ISSUE THREAD

**Issue by jeffderek** [ProfessorAire/Evands.Pellucid-Crestron#9]
Would like to be able to add a command like `MONitoring` and have it accept both `app monitoring verb` and `app mon verb`

**Comment by ProfessorAire** [comment]
Resolved and will be included in v1.1.0 release.

**Comment by jeffderek** [comment]
Aliases are shown on the primary help window for subcommands, but not for top level commands.

In the example below `app --help` shows the `systemmanager` command but does not show it's alias `sys`.  

`app systemmanager --help` shows the alias `sys` at the top, but for the `load` command the alias `lc` is shown.  Would like to see the `systemmanager` entry in `app -help` show as `systemmanager (sys)`

![image](https://user-images.githubusercontent.com/3788655/117661238-19101200-b16c-11eb-9c54-a61f804de23f.png)
